# Generated by Django 5.0.2 on 2024-02-23 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpetwell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=35)),
                ('genero', models.CharField(max_length=10)),
                ('edad', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'mascota',
            },
        ),
        migrations.CreateModel(
            name='PropietarioMascota',
            fields=[
                ('id_propietario', models.AutoField(primary_key=True, serialize=False)),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backpetwell.mascota')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backpetwell.usuario')),
            ],
        ),
    ]
