# Generated by Django 5.0.2 on 2024-02-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('apellido_usuario', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('contraseña', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
