# Generated by Django 5.0.2 on 2024-05-15 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backpetwell', '0004_veterinario_vacunacion_historialmedico_cita'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historialmedico',
            table='historial_medico',
        ),
        migrations.AlterModelTable(
            name='vacunacion',
            table='vacunacion',
        ),
        migrations.AlterModelTable(
            name='veterinario',
            table='veterinario',
        ),
    ]
