# Generated by Django 5.0.2 on 2024-05-15 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backpetwell', '0005_alter_historialmedico_table_alter_vacunacion_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cita',
            table='cita',
        ),
    ]
